### ISSUE TITLE
Graphs lacking detail and text is too small

### ISSUE THREAD

**Issue by Etoebben** [computationalmystic/augur-group26#10]
**The text in the graph is small  and we are missing the left side legend explaining the y axis are the percent of comments **
It is hard to read.

I would like the print to be a little larger font and the x and y axis better described

**Comment by Brendan-Thompson** [comment]
We fixed the issue of the graph's y-axis label not showing up by investigating the file: frontend/app/components/charts/CommitsNormalizedStackedBarChart.vue
We discovered that our y-axis was being set to null on line 162, and we simply deleted that line and the y-axis label appeared on the graph like we wanted.  

![axisFix](https://user-images.githubusercontent.com/47133414/57103251-e87a7f80-6cea-11e9-94a8-a01b430ef870.JPG)

Now that we had a label showing, I saw that it was displaying 'commits', because we were using code from a different metric. To fix this, I simply had to change the change function code to where I could have the y-axis field attribute set to 'percentage' and the y-axis on the graph shows the correct unit.
![percentageFix](https://user-images.githubusercontent.com/47133414/57112162-7b73e380-6d04-11e9-80ae-a18a35f6a07a.JPG)


As for the text size, we've decided that it's fine how it is now, but we might open it back up for the last sprint depending on the need.
